FROM python:3.12-slim

# Переменные окружения для Poetry
ENV PYTHONUNBUFFERED=1 

# Установка Poetry
RUN RUN pip install --upgrade pip wheel "poetry==2.1.3"
RUN poetry config virtualenvs.create false --local

WORKDIR /geo_tracker

# Установка зависимостей
COPY poetry.lock pyproject.toml ./
RUN poetry install

# Копируем весь проект
COPY . .

# Даем права на выполнение скрипта
RUN chmod +x wait-for-it.sh

# Запуск тестов
CMD ["pytest", "tests"]