FROM python:3.12-slim

WORKDIR /geo_tracker

COPY /app/requirements.txt ./
COPY wait-for-it.sh ./wait-for-it.sh
RUN pip install --no-cache-dir -r requirements.txt
RUN chmod +x wait-for-it.sh

COPY . .
RUN pip install pytest

CMD ["pytest", "tests"]