version: '3.9'

services:
  db:
    image: postgres:15
    restart: always

    environment:
      POSTGRES_USER: newest_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: geo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  test:
    build:
      context: .
      dockerfile: dockerfile.test 
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "pytest", "tests"]
    environment:
      SECRET_KEY: f4e96efed18a108f15904d3c67276410717981d49402f153d550fb9411d3537e
      DB_HOST: db
      DB_NAME: geo_db
      DB_PORT: 5432
      DB_USER: newest_user
      DB_PASSWORD: qwerty
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  pgdata: