version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: newest_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: geo_db
    volumes:
    - pgdata:/var/lib/postgesql/data

  web:
    build: .
    ports: 
    - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: geo_db
      DB_USER: newest_user
      DB_PASSWORD: qwerty
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  pgdata:
  
